Repository Smile-SA/elasticsuite, pull requests merged in 2025-03, with the labels that each got.

#3557 [Core] phpmd issue on request builder
  src/module-elasticsuite-core/Search/Request/Builder.php
Labels: safe to test

#3564 Allow providing a value for "missing" values in sort order params
  src/module-elasticsuite-core/Search/Request/SortOrder/SortOrderBuilder.php
Labels: needs update

#3563 [CatalogOptimizer] Move up and change label for 'Boost value (multipl…
  src/module-elasticsuite-catalog-optimizer/i18n/de_DE.csv
  src/module-elasticsuite-catalog-optimizer/i18n/en_US.csv
  src/module-elasticsuite-catalog-optimizer/i18n/fr_FR.csv
  src/module-elasticsuite-catalog-optimizer/i18n/nl_NL.csv
  src/module-elasticsuite-catalog-optimizer/view/adminhtml/ui_component/smile_elasticsuite_catalog_optimizer_form.xml
Labels: safe to test

#3562 [CatalogOptimizer] Scale function/factor dependant products exclusion
  src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Applier/AttributeValue.php
  src/module-elasticsuite-catalog-optimizer/i18n/de_DE.csv
  src/module-elasticsuite-catalog-optimizer/i18n/en_US.csv
  src/module-elasticsuite-catalog-optimizer/i18n/fr_FR.csv
  src/module-elasticsuite-catalog-optimizer/i18n/nl_NL.csv
  src/module-elasticsuite-catalog-optimizer/view/adminhtml/ui_component/smile_elasticsuite_catalog_optimizer_form.xml
Labels: enhancement, safe to test
